services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        command: bash -c "chown -R www-data:www-data storage bootstrap/cache && apache2-foreground"
